import { IWeather } from "./weatherInterface";

export interface IForecastData {
    wind_cdir: string,
    rh: number,
    pod: string,
    timestamp_utc: Date,
    pres: number,
    solar_rad: number,
    ozone: number,
    weather: IWeather,
    wind_gust_spd: number,
    timestamp_local: Date,
    snow_depth: number,
    clouds: number,
    ts: number,
    wind_spd: number,
    pop: number,
    wind_cdir_full: string,
    slp: number,
    dni: number,
    dewpt: number,
    snow: number,
    uv: number,
    wind_dir: number,
    clouds_hi: number,
    precip: number,
    vis: number,
    dhi: number,
    app_temp: number,
    datetime: Date,
    temp: number,
    ghi: number,
    clouds_mid: number,
    clouds_low: number
}
